FROM golang:1.22

ENV NVM_DIR /root/.nvm
ENV NODE_VERSION 20.12.1

# Install necessary packages
RUN apt update && apt install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# Add Node.js and npm to path so the commands are available
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install github.com/cosmtrek/air@latest 

# Copy necessary files for the Makefile to run
COPY ./config /usr/src/app/config
COPY ./Makefile /usr/src/app

WORKDIR /usr/src/app

# Run the make init command to initialize the project
RUN make init
RUN mv /usr/src/app/config/init.sh /usr/src/app/init.sh

COPY . .

