# CREATE A SCRIPT TO SET THE MOD NAME ACCORDING TO THE FOLDER APP NAME
# CREATE THE MAIN.GO FILE AND POPULATE IT WITH THE MAIN FUNCTION TO RUN SERV AND TEMPL
# CREATE .TEMPL FILE TO BE USED AS A TEMPLATE FOR THE MAIN.GO FILE
# CREATE REMOTLY THE REPO IN GITHUB BASED ON APP NAME WITH GH CLI
